### ISSUE TITLE
fix: Missing Dynamic Key for `<div>`

### ISSUE THREAD

**Issue by bliutech** [uclaacm/acmcyber.com#106]
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at button
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///./pages/archive.tsx:24:78)
    at main
    at App (webpack-internal:///./pages/_app.tsx:18:16)
    at StyleRegistry (/Users/bliu/Documents/acmcyber.com/.yarn/__virtual__/styled-jsx-virtual-3270619731/0/cache/styled-jsx-npm-5.1.1-2557a209ba-523a33b386.zip/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/bliu/Documents/acmcyber.com/.yarn/__virtual__/next-virtual-e3eadb3498/0/cache/next-npm-13.2.1-585715321e-2dba145ef4.zip/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
    at AppContainer (/Users/bliu/Documents/acmcyber.com/.yarn/__virtual__/next-virtual-e3eadb3498/0/cache/next-npm-13.2.1-585715321e-2dba145ef4.zip/node_modules/next/dist/server/render.js:291:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/bliu/Documents/acmcyber.com/.yarn/__virtual__/next-virtual-e3eadb3498/0/cache/next-npm-13.2.1-585715321e-2dba145ef4.zip/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/bliu/Documents/acmcyber.com/.yarn/__virtual__/next-virtual-e3eadb3498/0/cache/next-npm-13.2.1-585715321e-2dba145ef4.zip/node_modules/next/dist/server/render.js:614:21)
```

**Comment by Arc-blroth** [comment]
I'm like 99% sure this was resolved a long time ago lol
